.github/workflows/upload_test_results_to_biquery.yaml
upload-test-results/parse_test_results.py

Increases error logging on bigquery python script
waits for result of load, including error status
removes autodetect, which is incorrectly casting datatypes.

Ddo 2930 fix bq call

---

upload-test-results/parse_test_results.py

switches to -1 array notation in case of non `class` error types

Ddo 2377 fix bq script

---

e2e-test/e2etest.py

`e2etest.py` has the line `from helper import *`.  `helper.py` used to import time but that line was removed in https://github.com/broadinstitute/dsp-reusable-workflows/pull/8, so this PR puts it back into `e2etest.py` where it is still needed.

AJ-1396 reinstate time

---

.github/workflows/run-e2e-tests.yaml

I renamed the test script as part of the previous AJ-1397 PR, but did not include the name change in the github actions file. This is causing the wds clone e2e test to fail.

AJ-1397 - Add workspace deletion to wds e2e test

---

e2e-test/helper.py

Forgot to include the function import in helper file, the benefit of this bug was this allowed to test the fact that deletion doesnt actually overall fail the test.

AJ-1397 - Add missing function import

---

e2e-test/helper.py
e2e-test/wds_azure_e2etest.py

When deletion of workspace was added for clean up after the e2e test, we didnt add deletion for the cloned workspace. This change deletes the workspace clone if the clone was successful.

AJ-1397 - Delete cloned workspace

---

e2e-test/app_helper.py

https://github.com/broadinstitute/dsp-reusable-workflows/pull/20 added extra polling in the case of an app not appearing in the app list at all.  However, this method is used in some cases to check for the existence of an app at all (as opposed to expecting the app to exist and simply waiting for it to be ready), and in reality an app should be in the list returned from Leo by the time this method is called.  This PR removes that extra polling.

AJ-1436 Don't poll if app doesn't exist

---

e2e-test/cromwell_azure_e2e_test.py

Increase wait time before we give up on a workflow and fail from about 11 minutes to about 15 minutes. I've seen that in successful test runs, workflows often take close to the 11 minutes to finish.

WX-1419 Increase wait time for workflow to complete

---

e2e-test/wds_azure_e2etest.py

Make sure the test errors with a correct error message if WDS in a cloned workspace failed to start.

AJ-1791 - Log error if wds on cloned workspace fails to start

---

e2e-test/tsps_e2e_test.py

Update the TSPS e2e test so that new input validation introduced in https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/75 won't cause the test to fail.
See ticket https://broadworkbench.atlassian.net/browse/TSPS-195

TSPS-195 add valid inputs to tsps create job request

---

e2e-test/helper.py
e2e-test/wds_azure_e2etest.py

https://broadworkbench.atlassian.net/browse/AJ-1398
When the wds test was originally written, it had flags for whether or not to run workflows with the expectation that those apps would also be tested.  Workflows instead wrote separate test files, leaving all the workflows-related flags unused in the wds test.  This PR removes this unused code and should not have any difference in behavior, and certainly should not affect any non-wds test.  For stewards of the other tests, please verify that your tests are not affected.

AJ-1398 remove workflows from wds test

---

e2e-test/tsps_e2e_test.py

This PR https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/94 included a change of the user-provided input keys to teaspoons from snake_case to camelCase. here we update the teaspoons e2e test to reflect that change.

TSPS-246 teaspoons now takes camelCase inputs

---

.github/workflows/can-i-deploy.yaml

Have to add the secrets explicitly, annoyingly, secrets: inheirit works fine.... if both projects are in broadinstitute, but dies silently if databiosphere tries to use it. (it doesn't error, it just doesn't pass the secrets, which of course breaks the flow)

add secrets explicitly

---

.github/actions/run-publish-contracts/action.yaml

copies code from terra-github-workflows. removes vault calls and uses github secrets instead.

move the publish-contracts action to dsp-reusable

---

e2e-test/resources/tsps/tsps_gcp_set_up_control_workspace.py
e2e-test/workspace_helper.py

this new workspace creation script:
- works in any environment (except BEEs)
- creates a GCP workspace with enhanced logging + auth domain
- shares with Teaspoons SA (as owner) if one is included in script input params
- allows sharing with other accounts (e.g. teaspoons developers group)
- imports WDL - either the real WDL or empty WDL, ultimately named ImputationBeagle - with config set up as much as possible
Example command in dev:
```python e2e-test/resources/tsps/tsps_gcp_set_up_control_workspace.py -t `gcloud auth print-access-token marymorg.dev@gmail.com` -e dev -p teaspoons-imputation-dev -w test-imputation-workspace-dev-1 -a teaspoons-imputation-workspace-auth-domain -s teaspoons-developers-dev@dev.test.firecloud.org --use-empty-wdl```
ticket: …

TSPS-281 Create Teaspoons Imputation Service workspace creation script for GCP

---

.github/workflows/upload_test_results_to_biquery.yaml

updates github actions to avoid deprecation warnings.

AJ-2027: update actions in upload_test_results_to_biquery

---

e2e-test/tsps_gcp_e2e_test.py

to address the test failure here - https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/11943565231/job/33293144545
because of the changes made in https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/162/files

fix admin piplines api call in teaspoons e2e test

---

e2e-test/teaspoons_gcp_e2e_test.py

We moved the user-provided description input from the `start` endpoint payload to the `prepare` endpoint payload. This PR makes that update in the e2e test.
Teaspoons PR: https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/180
Jira ticket: https://broadworkbench.atlassian.net/browse/TSPS-388

TSPS-388 Teaspoons e2e test: move description input from start endpoint to prepare endpoint

---

e2e-test/teaspoons_helper.py

This is a redo of this PR: https://github.com/broadinstitute/dsp-reusable-workflows/pull/60
Which was accidentally reverted in this PR: https://github.com/broadinstitute/dsp-reusable-workflows/pull/59/files#diff-9709ae917f41eaa6a096c695fd5356a292dd5ef60ed82b1eeaf8851330a7dcd5
Jira ticket: https://broadworkbench.atlassian.net/browse/TSPS-388

TSPS-388 redo: move description from start to prepare endpoint

---

.github/workflows/run_teaspoons_e2e_cli_tests.yaml

Poetry 2.0.0 update broke our e2e test; the workaround specified [here](https://github.com/python-poetry/poetry/issues/9961) and implemented by us [here](https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/pull/25) ended up breaking our build. So for now we'll pin poetry to version 1.8.5 (the last working version we had before the update to 2.0.0) until poetry fixes this bug.
Test run: https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/actions/runs/12639177524
Companion PR in CLI repo to revert the previous workaround, which broke our build. https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/pull/26

Teaspoons CLI e2e test: Pin poetry version for fix for poetry 2.0.0 bug

---

.github/workflows/run_teaspoons_e2e_cli_tests.yaml

We changed the way users specify inputs to the Teaspoons CLI (terralab). This PR makes that update in our e2e test.
Teaspoons CLI PR: https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/pull/23
Test run: https://github.com/DataBiosphere/terra-scientific-pipelines-service-cli/actions/runs/12695336306

TSPS-346 Update Teaspoons CLI e2e test to use arbitrary pipeline input specification

---

e2e-test/resources/teaspoons/teaspoons_gcp_set_up_control_workspace.py
e2e-test/workspace_helper.py

Minor updates were required in the script to create an Imputation Control Workspace in staging to go along with Teaspoons' release to staging.
- Add wdl version as an input argument to the script to ensure we're using the correct one and avoid hardcoding
- Add setting of TTL on workspace bucket
Tested in dev and on staging workspace, TTL successfully set on staging workspace:
Jira ticket: https://broadworkbench.atlassian.net/browse/TSPS-410

TSPS-410 Updates to Teaspoons Imputation workspace creation script for staging

---

.github/workflows/upload_test_results_to_biquery.yaml

`download-artifact@v3` no longer works: https://github.com/marketplace/actions/download-a-build-artifact
This PR removes the reference to it.

CORE-205: remove download-artifact@v3

---

e2e-test/teaspoons_gcp_e2e_cli_test_setup.py
e2e-test/teaspoons_gcp_e2e_service_test.py
e2e-test/teaspoons_helper.py

We are seeing some transient failures when running our e2e tests where rawls/orch cant talk to sam due to unknown host exceptions.  We're seeing if pinging sam before running our tests can help with this issue.

TSPS-434 ping sam before running teaspoons e2e tests

---

e2e-test/teaspoons_gcp_e2e_cli_test_setup.py
e2e-test/teaspoons_gcp_e2e_service_test.py

We've been seen an uptick in transient failures with our e2e test due to unknown host exceptions.  We had a discussion in [slack](https://broadinstitute.slack.com/archives/C07QQ3L0AHX/p1738604418720059) and for now this seems like the most reasonable way forward.

TSPS-434 adding a sleep to the start of the teaspoons e2e test to avoid unknown host exceptions

---

e2e-test/teaspoons_helper.py

This is necessary for changes made to teaspoons in https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/207 to the version of the array_imputation version.  I think these are the only places that need to change

update array_imputation to version 1 to match service changes

---

e2e-test/teaspoons_gcp_e2e_cli_test_setup.py
e2e-test/teaspoons_gcp_e2e_service_test.py

We're seeing a steady occurrence  of failures due to batch and there arent really any logs we could find ourselves or through google support that have any information as to what is happening so we're trying a 5 min sleep in between creating the google project and launching the batch job 🤷

TSPS-473 add 5 min sleeps to teaspoons e2e

---

.github/workflows/run_teaspoons_e2e_cli_tests.yaml
.github/workflows/run_teaspoons_e2e_service_tests.yaml
e2e-test/teaspoons_gcp_e2e_cli_test_setup.py
e2e-test/teaspoons_gcp_e2e_service_test.py
e2e-test/teaspoons_helper.py

Due to changes made in https://github.com/DataBiosphere/terra-scientific-pipelines-service/pull/223 we need to update our test to not expect users to have some non zero default quota when submitting a pipelines.  This updates the service and cli e2e tests to make it work
This should be merged before the service PR
Example GHA running successfully with these changes and service changes made in previously linked PR
https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/15354167655/job/43209819021

TSPS-508 update teaspoons e2e test to work with 0 default quota pipelines
